# Generated by Django 2.2.3 on 2019-07-28 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 7, 28, 8, 23, 52, 94627, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
